### ISSUE TITLE
conversation with dumbass who stalks me on all his accounts and who became trans for a day 🤣🤣🤣

### ISSUE THREAD

**Issue by ghost** [WeHateYouXYXS/Eggsploit#1]
that it is the issue but what?

**Comment by wehateyouvvita** [comment]
didnt ask

**Comment by ghost** [comment]
k xyxs basically stfu and stop shitting about me to everyone

**Comment by ghost** [comment]
unfunny mf

**Comment by wehateyouvvita** [comment]
never asked “emilia”

**Comment by ghost** [comment]
k well fuck urself

**Comment by ghost** [comment]
do we start drama about this again or u stfu

**Comment by wehateyouvvita** [comment]
didnt ask “emilia”

**Comment by ghost** [comment]
lmfao

**Comment by ghost** [comment]
im not emilia anymore

**Comment by wehateyouvvita** [comment]
how nice “emilia” but i didnt ask

**Comment by ghost** [comment]
how dumb ru

**Comment by wehateyouvvita** [comment]
didnt ask “emilia”

**Comment by ghost** [comment]
didnt ask "kadin"

**Comment by wehateyouvvita** [comment]
dont care

**Comment by ghost** [comment]
dont care

**Comment by wehateyouvvita** [comment]
didnt ask latvian trans girl

**Comment by ghost** [comment]
and ur a pakistan black pedo mf

**Comment by wehateyouvvita** [comment]
pedo? im 14 and im not even black 🤣

**Comment by ghost** [comment]
k

**Comment by wehateyouvvita** [comment]
stop joining my servers on alt accounts “emilia”

**Comment by ghost** [comment]
half japan half pakistan half fucking every country half idfk basically fuck yourself and thanks for your death threats before

**Comment by ghost** [comment]
chuan and gmod11fan were my alts lo

**Comment by wehateyouvvita** [comment]
do you think i didnt know lmfao kys

**Comment by ghost** [comment]
no you kys

**Comment by ghost** [comment]
alot stuff i have to do in life

**Comment by wehateyouvvita** [comment]
what stalk me on all ur accs?

**Comment by ghost** [comment]
no lmfao

**Comment by wehateyouvvita** [comment]
weird ass russian wannabe

**Comment by YoPoster** [comment]
i am half russian u nigger

**Comment by ghost** [comment]
now fr bye forever and fuck you

**Comment by wehateyouvvita** [comment]
didnt ask

**Comment by ghost** [comment]
dont care what you didn't ask

**Comment by YoPoster** [comment]
ok nigger

**Comment by wehateyouvvita** [comment]
didnt ask

**Comment by wehateyouvvita** [comment]
“ghost”
